name: Run Tests

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js and Yarn
      uses: borales/actions-yarn@v2
      with:
        node-version: '14'  # Replace with your Node.js version

    - name: Install dependencies
      run: yarn install  # Use yarn for installing dependencies

    - name: Run tests
      run: yarn test  # Use yarn for running tests
